version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

volumes:
  redis-data:
