version: "3.8"

services:
  redis-shard-1:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data-1:/var/lib/redis
    command: redis-server --appendonly yes

  redis-shard-2:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data-2:/var/lib/redis
    command: redis-server --appendonly yes

  redis-shard-3:
    image: redis
    ports:
      - "6381:6379"
    volumes:
      - redis-data-3:/var/lib/redis
    command: redis-server --appendonly yes

  redis-shard-4:
    image: redis
    ports:
      - "6382:6379"
    volumes:
      - redis-data-4:/var/lib/redis
    command: redis-server --appendonly yes

  redis_queue:
    image: redis
    ports:
      - "6378:6379" # Sử dụng cổng 6378 để tránh trùng với cổng của các redis khác
    volumes:
      - redis-queue-data:/var/lib/redis
    command: redis-server --appendonly yes # Bạn có thể thêm các tùy chọn cấu hình khác nếu cần

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  # mysql:
  #   image: mysql
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: 123456
  #   volumes:
  #     - mysql-data:/var/lib/mysql

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-queue-data:
  mongo-data:
  mysql-data:
